name: Validate
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10 # package.json の packageManager フィールドに合わせる
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm' # pnpm のキャッシュを有効化
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm -r exec tsc --noEmit
      - name: Check lint
        run: pnpm lint
      - name: Test
        run: pnpm -r test
