name: Validate
on: push
jobs:
  validate: #a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm' # pnpm のキャッシュを有効化
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm -r exec tsc --noEmit
      - name: Check lint
        run: pnpm lint
      - name: Test
        run: pnpm -r test
      - name: Build frontend
        working-directory: ./packages/front # フロントエンドのディレクトリに移動
        run: pnpm build
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: packages/front/dist # 複数ファイルが含まれるパスを指定するとzipになる
